# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://lokhinw.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "MLHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "InspireHacks | 15/16 April 2017"
  description: "This is a sample hackathon website that you can use by following instructions on GitHub."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "InspireHacks"
  description: "Inspire. Accelerate. Grow"
  date:        "April 22-23, 2017"
  location:    "Markham, Ontario, Canada"

  trust_badge:
    year:   "2017"  # season year
    region: "na"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        my_mlh:
          client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
          redirect_uri: "https://mlh.github.io/mlh-hackathon-boilerplate/success.html"
      - text: "Sponsor"
        href: "mailto:keshav.chawla@jectoronto.com"
      - text: "Mentor"
        href: "#"

  about:
    description: >
      Example Hacks is a hackathon hosted at The University of Example.
      This is your opportunity to describe your event, what to expect, where it is & anything unique to your event.
      Keep it straightforward, don't make it too long.

  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "INSPIRE."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image2.png"
        title: "ACCELERATE."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image3.png"
        title: "GROW."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.

  # Frequently asked questions.
  faq:
    - question: "what_is_a_hackathon?"
      answer: >
        A hackathon is an invention marathon. Students come together to build cool
        software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "how_much_does_it_cost?"
      answer: >
        Nothing. Attending is free. Food and prizes are on us!
    - question: "do_i_need_to_be_a_student_to_attend?"
      answer: >
        Yes. Only students who are currently enrolled at a highschool or have graduated within the past 12 months are eligible to attend.
    - question: "where_is_this_event?"
      answer: >
        The event is being hosted at Markville Secondary School.
    - question: "what_is_major_league_hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "is_there_a_code_of_conduct?"
      answer: >
        Yes there is. We enforce it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).
    - question: "ok_if_no_experience?"
      answer: >
         That's completely fine! You'll have plenty of opportunity to pick the brains of talented students around you. Furthermore, we will help you get started or learn something new!
    - question: "what_to_build?"
      answer: >
        You can build whatever you want: websites, programs, mobile apps, anything! However, all code must be written during the hackathon - feel free to use open source libraries and APIs.
    - question: "num_people_per_team"
      answer: >
        We recommend working in teams of 3-4 people, though participants in the past have worked solo or in pairs as well. However, if your team would like to submit your project for prize consideration, we have a hard limit of 4 members per team.
    - question: "not_a_hacker"
      answer: >
        You can help by sponsoring the event. You can also spread the word about this event to students, friends, and media.
  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
